require'telescope'.setup {}

vim.api.nvim_set_keymap('n', '<leader>ff', [[<cmd>lua require('telescope.builtin').find_files()<CR>]], {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>fe', [[<cmd>lua require('telescope.builtin').file_browser()<CR>]], {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>fo', [[<cmd>lua require('telescope.builtin').vim_options()<CR>]], {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>fk', [[<cmd>lua require('telescope.builtin').keymaps()<CR>]], {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>fm', [[<cmd>lua require('telescope.builtin').man_pages()<CR>]], {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>fb', [[<cmd>lua require('telescope.builtin').buffers()<CR>]], {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>fw', [[<cmd>lua require('telescope.builtin').current_buffer_fuzzy_find()<CR>]], {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>ft', [[<cmd>lua require('telescope.builtin').tags()<CR>]], {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>fy', [[<cmd>lua require('telescope.builtin').tags{only_current_buffer = true}<CR>]],
                        {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>f?', [[<cmd>lua require('telescope.builtin').oldfiles()<CR>]], {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>fs', [[<cmd>lua require('telescope.builtin').grep_string()<CR>]], {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>fj', [[<cmd>lua require('telescope.builtin').live_grep()<CR>]], {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>fgc', [[<cmd>lua require('telescope.builtin').git_commits()<CR>]], {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>fgb', [[<cmd>lua require('telescope.builtin').git_branches()<CR>]], {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>fgs', [[<cmd>lua require('telescope.builtin').git_status()<CR>]], {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>fgp', [[<cmd>lua require('telescope.builtin').git_bcommits()<CR>]], {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>fls', [[<cmd>lua require('telescope.builtin').lsp_document_symbols()<CR>]], {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>fld', [[<cmd>lua require('telescope.builtin').lsp_definitions()<CR>]], {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>flr', [[<cmd>lua require('telescope.builtin').lsp_references()<CR>]], {noremap = true, silent = true})
